---
server:
    install: '1'
    packages: [vim, git]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: govinda, ip: 192.168.1.99, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: '0' }
apache:
    install: '1'
    docroot: /vagrant
    servername: vagrant/www
mysql:
    install: '1'
    root_password: root
    database: db
    user: user
    password: password
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-gd, php5-mysql]

